# Generated by Django 4.1.5 on 2023-01-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendLibaryAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('author_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('isbn', models.IntegerField(max_length=13)),
                ('date_of_publication', models.DateField()),
                ('quantity', models.IntegerField()),
                ('book_description', models.TextField()),
                ('language', models.TextField()),
                ('author_id', models.ManyToManyField(to='BackendLibaryAPI.author')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='BookModel',
        ),
        migrations.AddField(
            model_name='book',
            name='category_id',
            field=models.ManyToManyField(to='BackendLibaryAPI.category'),
        ),
    ]
