# Generated by Django 4.1.5 on 2023-01-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendLibaryAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='category_id',
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='books', to='BackendLibaryAPI.author'),
        ),
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='books', to='BackendLibaryAPI.category'),
        ),
    ]
